server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerceApp
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import: "classpath:env.properties"
  jpa:
    hibernate:
      ddl-auto: update  # Automatically update the database schema
#    show-sql: true  # Show SQL queries in the console
#    properties:
#      hibernate:
#        format_sql: true  # Format SQL queries for readability
#        use_sql_comments: true  # Add comments to SQL queries for context

  security:
    user:
      name: user
      password: password
jwt:
  secret: "sM4Rj5w69It5YcxUo7g6h9F5zYwHkv8aT7JvMZmglH0="
  expiration: 86400000  # 1 day in milliseconds

app:
  resetPassword:
    expiryTimeInMinutes: 60
